blank_issues_enabled: false
contact_links:
  - name: Feature request
    about: Propose any new features here on our ideas board
    url: https://github.com/shellhub-io/shellhub/discussions/categories/ideas
  - name: Question
    about: Ask the community a question
    url: https://github.com/shellhub-io/shellhub/discussions/categories/q-a
